### ISSUE TITLE
Proposal to extract retrieval of namespace declarations from ManagedClassProcessor to public API class

### ISSUE THREAD

**Issue by JensPiegsa** [kbss-cvut/jopa#196]
I'm in the process of writing a generic DAO base class for our project, inspired by the [provided examples](https://github.com/kbss-cvut/jopa-examples/blob/master/jsonld/src/main/java/cz/cvut/kbss/jopa/jsonld/persistence/dao/BaseDao.java). Specifically, I aim to properly support entity classes that make use of IRI prefixes declared via `@Namespace` annotation.

In order to implement general queries within this DAO base class, I need to resolve all declared namespaces.

The `cz.cvut.kbss.jopa.utils.NamespaceResolver` is one part of the equation, but it requires me to manually register all prefixes and namespaces.

The `cz.cvut.kbss.jopa.model.metamodel.ManagedClassProcessor` is the other part, collecting all namespace declarations from an entity class, all its parent classes, and their respective packages. However, this class is not part of the public API.

Given this, I'd like to hear your thoughts about extracting the @namespace retrieval code from `ManagedClassProcessor` into a new, non-static public class.

In my understanding this would make the `@Namespace` annotation more useful and help to build general queries for arbitrary entity classes.

**Comment by ledsoft** [comment]
Hi,
I am certainly not against this idea. However, do you mean extracting it including the parent classes and packages traversal? Because that is done by the metamodel builder intentionally so that there is only one traversal required.

If you mean just extracting the processing of a single type and its namespaces (basically what the `ManagedClassProcessor.detectNamespaces` method does), that is easy to do. It might suffice to just make the method (and the enclosing class) public.
