### ISSUE TITLE
Recursive serialization?

### ISSUE THREAD

**Issue by YanDoroshenko** [kbss-cvut/jopa#34]
I have two entities - FunctionsDTO (one <=> many) FunctionDTO, mapped like this:
```
@OWLClass(iri = s_c_functions_dto)
public class FunctionsDTO extends AbstractEntity {
    @Sequence
    @OWLDataProperty(iri = s_p_has_function_dto, fetch = FetchType.EAGER)
    private List<FunctionDTO> functions;
...
}
```
```
@OWLClass(iri = s_c_function_dto)
public class FunctionDTO extends AbstractEntity {
...
}
```
The problem is that serialization only works on the top level of the hierarchy:
```
{
      "http://onto.fel.cvut.cz/ontologies/s-pipes/has-function-dto" : {
         "@list" : [
            "cz.cvut.kbss.spipes.model.dto.FunctionDTO@316840ee",
            "cz.cvut.kbss.spipes.model.dto.FunctionDTO@2a176721",
            "cz.cvut.kbss.spipes.model.dto.FunctionDTO@63226973"
         ]
      },
      "@type" : [
         "http://onto.fel.cvut.cz/ontologies/s-pipes/functions-dto"
      ]
   }
```
Am I doing something wrong?

**Comment by ledsoft** [comment]
This is a JB4JSON-LD question... If you mean that the `FunctionDTO` items in the list are being serialized using `toString`, this is probably because the attribute has to be an `OWLObjectProperty`. `OWLDataProperty` is used to reference literal values, `OWLObjectProperty` references other individuals.

**Comment by YanDoroshenko** [comment]
@ledsoft Oh, of course. Thanks.
