### ISSUE TITLE
Give more semantics to the disambiguation of duplicate concepts in OWL2Java

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/jopa#85]
Currently, OWL2Java disambiguates concepts with the same local name by letter prefixes, e.g. `s_p_Comment` and `s_p_Comment_A` denoting two concepts with local name Comment coming from two different namespaces. 

Instead of letter suffixes generate duplicate terms according to the prefix of the vocabulary used.

**Comment by ledsoft** [comment]
Note that this also applies to generated class names in the model. If there are two class IRIs with the same local name (e.g., `http://purl.org/dc/terms/Agent` and `http://xmlns.com/foaf/0.1/Agent`), they would both have the same simple class name `Agent`. Following #199, this has been fixed by appending the `_A` suffix the same way it is done to `Vocabulary` constants.
However, such a solution is not satisfactory and OWL2Java should attempt to use the prefix of the vocabulary (if available) to disambiguate such concepts.
